version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

  pre_build:
    commands:
      - echo Setting environment variables...
      - REPOSITORY_URI=211125588626.dkr.ecr.us-east-1.amazonaws.com/deploy-game-app
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=latest

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG

